# Generated by Django 5.1.4 on 2025-01-01 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_bankaccountorganization_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccountorganization',
            name='payment_purpose',
        ),
    ]
