# Generated by Django 5.1.4 on 2024-12-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='Введите номер телефона', unique=True, verbose_name='телефонный номер'),
        ),
    ]
