# Generated by Django 5.1.4 on 2025-01-01 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_bankaccountorganization_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccountorganization',
            name='account_number',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(10000000000000000000), django.core.validators.MaxValueValidator(99999999999999999999)], verbose_name='расчетный счет'),
        ),
    ]
