# Generated by Django 5.1.4 on 2025-01-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_bankaccountorganization_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccountorganization',
            name='bic_code',
            field=models.CharField(max_length=11, verbose_name='БИК банка'),
        ),
        migrations.AlterField(
            model_name='bankaccountorganization',
            name='tin_number',
            field=models.CharField(max_length=12, verbose_name='ИНН'),
        ),
    ]
