# Generated by Django 5.1.4 on 2025-01-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_bankaccountorganization_bic_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountorganization',
            name='card_number',
            field=models.CharField(default=6207456912345432, help_text='Введите номер карты', max_length=20, verbose_name='Номер карты'),
            preserve_default=False,
        ),
    ]
