# Generated by Django 5.1.4 on 2025-01-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_bankaccountorganization_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccountorganization',
            name='account_number',
            field=models.CharField(help_text='Введите номер счета', max_length=20, verbose_name='расчетный счет'),
        ),
        migrations.AlterField(
            model_name='bankaccountorganization',
            name='bic_code',
            field=models.CharField(help_text='Введите БИК банка', max_length=11, verbose_name='БИК банка'),
        ),
        migrations.AlterField(
            model_name='bankaccountorganization',
            name='tin_number',
            field=models.CharField(help_text='Введите индивидуальный номер налогоплательщика', max_length=12, verbose_name='ИНН'),
        ),
    ]
