# Generated by Django 5.1.4 on 2024-12-25 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0004_alter_schedule_date_time_alter_schedule_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekdays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(help_text='Введите время занятий', verbose_name='время занятий')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='дата и время обновления')),
                ('address', models.ManyToManyField(to='theatre.address', verbose_name='адрес мероприятия')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.event', verbose_name='наименование мероприятия')),
                ('teacher', models.ManyToManyField(related_name='teacher', to='theatre.teacher', verbose_name='педагог')),
                ('weekdays', models.ManyToManyField(to='theatre.weekdays', verbose_name='день недели')),
            ],
            options={
                'verbose_name': 'расписание',
                'verbose_name_plural': 'расписания',
            },
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
