# Generated by Django 5.1.4 on 2024-12-25 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0005_weekdays_classschedule_delete_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='address',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='theatre.address', verbose_name='адрес мероприятия'),
            preserve_default=False,
        ),
    ]
