# Generated by Django 5.1.4 on 2024-12-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0006_remove_classschedule_address_classschedule_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='weekdays',
        ),
        migrations.DeleteModel(
            name='Weekdays',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='weekdays',
            field=models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'суббота'), ('sunday', 'воскресенье')], default=0, verbose_name='день недели'),
            preserve_default=False,
        ),
    ]
