# Generated by Django 5.1.4 on 2024-12-25 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0009_alter_weekdays_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaybillSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(help_text='Введите дату и время мероприятия', verbose_name='дата и время мероприятия')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='дата и время обновления')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='theatre.address', verbose_name='адрес мероприятия')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='theatre.event', verbose_name='наименование мероприятия')),
                ('teacher', models.ManyToManyField(related_name='teacher_big_event', to='theatre.teacher', verbose_name='педагог')),
            ],
        ),
        migrations.CreateModel(
            name='RegularClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(help_text='Введите время занятий', verbose_name='время занятий')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='дата и время обновления')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='theatre.address', verbose_name='адрес мероприятия')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='theatre.event', verbose_name='наименование мероприятия')),
                ('teacher', models.ManyToManyField(related_name='teacher_regular_event', to='theatre.teacher', verbose_name='педагог')),
                ('weekdays', models.ManyToManyField(help_text='Выберите дни недели', to='theatre.weekdays', verbose_name='день недели')),
            ],
            options={
                'verbose_name': 'расписание регулярного занятия',
                'verbose_name_plural': 'расписание регулярных занятий',
            },
        ),
        migrations.DeleteModel(
            name='ClassSchedule',
        ),
    ]
