# Generated by Django 5.1.4 on 2024-12-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0011_alter_playbillschedule_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbillschedule',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='playbill_event_pict/', verbose_name='Фотка мероприятия'),
        ),
        migrations.AddField(
            model_name='regularclassschedule',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='regular_event_pict/', verbose_name='Фотка мероприятия'),
        ),
    ]
