# Generated by Django 5.1.4 on 2024-12-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0012_playbillschedule_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularclassschedule',
            name='price',
            field=models.FloatField(default=0, help_text='Введите стоимость услуги', verbose_name='Стоимость'),
        ),
    ]
