# Generated by Django 5.1.4 on 2024-12-28 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0014_remove_teacher_teachers_teacher_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='image_teachers',
            new_name='image',
        ),
    ]
