# Generated by Django 5.1.4 on 2025-01-07 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0015_rename_image_teachers_teacher_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(help_text='Вставьте фотографию', upload_to='image_gallery/', verbose_name='Фотография')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.playbillschedule', verbose_name='мероприятие')),
            ],
        ),
    ]
