# Generated by Django 5.1.4 on 2025-01-07 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0016_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'галерея', 'verbose_name_plural': 'галерея'},
        ),
    ]
