# Generated by Django 5.1.4 on 2025-01-08 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0017_alter_gallery_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='name',
        ),
    ]
