# Generated by Django 5.1.4 on 2025-01-09 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0018_remove_gallery_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='theatre.playbillschedule', verbose_name='мероприятие'),
        ),
    ]
