# Generated by Django 5.1.4 on 2025-01-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0019_alter_gallery_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='mark_deletion',
            field=models.BooleanField(default=False),
        ),
    ]
