# Generated by Django 5.1.4 on 2025-01-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0020_gallery_mark_deletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата и время создания'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='дата и время обновления'),
        ),
    ]
