# Generated by Django 5.1.4 on 2025-01-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0021_gallery_creation_date_gallery_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
        migrations.AddField(
            model_name='gallery',
            name='photo',
            field=models.ImageField(blank=True, help_text='Вставьте фотографию', null=True, upload_to='image_gallery/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='video',
            field=models.FileField(blank=True, help_text='Вставьте видео', null=True, upload_to='video_gallery/', verbose_name='Видеофайл'),
        ),
    ]
