# Generated by Django 5.1.4 on 2025-01-12 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0022_remove_gallery_image_gallery_photo_gallery_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='video',
            field=models.FileField(blank=True, help_text='Вставьте видео', null=True, upload_to='video_gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('.mp4', '.avi', '.mpg', '.mov', '.wmv', '.wma', '.mkv', '.flv', '.f4v', '.webm', '.avchd', '.mpeg', '.3gp', '.m4v'))], verbose_name='Видеофайл'),
        ),
    ]
