# Generated by Django 5.1.4 on 2025-01-12 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0023_alter_gallery_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='creation_date',
            new_name='creation_datetime',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='updated_date',
            new_name='updated_datetime',
        ),
    ]
